name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          config-file: release-please-config.json
          
      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
        if: ${{ steps.release.outputs.release_created }}
      
      - name: Install dependencies
        run: npm ci
        if: ${{ steps.release.outputs.release_created }}
      
      - name: Build package
        run: npm run prepublishOnly
        if: ${{ steps.release.outputs.release_created }}
      
      - name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: npm publish --access public
        if: ${{ steps.release.outputs.release_created }}
